// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDsBLCFmgC9dRDT6YcWk_JJnEd--G0Ld0',
    appId: '1:577176829025:android:49b75b29a0b90c9bf8be20',
    messagingSenderId: '577176829025',
    projectId: 'be-your-stories',
    storageBucket: 'be-your-stories.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA95g-BFCIrQRUXyKoY0VNWCEtmj4JgenA',
    appId: '1:577176829025:ios:cc6ef05c45f1f790f8be20',
    messagingSenderId: '577176829025',
    projectId: 'be-your-stories',
    storageBucket: 'be-your-stories.firebasestorage.app',
    androidClientId:
        '577176829025-7n7d9ougjkhr4b1bap9i93inqv90ai0k.apps.googleusercontent.com',
    iosClientId:
        '577176829025-as2cocosifcgbrcriokpks7r6m8av8jo.apps.googleusercontent.com',
    iosBundleId: 'beyourstories.com.br.app',
  );
}
